### ISSUE TITLE
文件夹内任务显示不全

### ISSUE THREAD

**Issue by Rainmna** [woolson/microsoft-todo-mac#10]
我有一个文件夹，叫做购物，里面一共有4个任务，都有好几个步骤。
但是只显示了两个任务，另外两个不论是同步，还是退出后重新打开，都无法显示出来。

**Comment by woolson** [comment]
@Rainmna 请问：【购物】任务是和别人共享的任务吗？目前无法显示共享任务（微软接口未返回相关数据），微软目前未开放步骤的接口（好DT😂），我后面再看看官方文档，如果有提供会尽快更新上去的。谢谢。

**Comment by woolson** [comment]
参见 #11

**Comment by Rainmna** [comment]
> @Rainmna 请问：【购物】任务是和别人共享的任务吗？目前无法显示共享任务（微软接口未返回相关数据），微软目前未开放步骤的接口（好DT😂），我后面再看看官方文档，如果有提供会尽快更新上去的。谢谢。

哈哈😂，没有人跟我共享购物车啊，从来没用过共享功能～
期待新功能可以早日实现，微软再给力一点，接口要给都给，利索点。
