### ISSUE TITLE
数据不全

### ISSUE THREAD

**Issue by mzlogin** [woolson/microsoft-todo-mac#12]
这是在本应用里看到的：

![image](https://user-images.githubusercontent.com/1646590/57436667-bc26ac00-7272-11e9-8af4-bac3720d565e.png)

这是在 Android APP 里看到的：

![image](https://user-images.githubusercontent.com/1646590/57436761-f8f2a300-7272-11e9-801c-1699709741d9.png)

反复点设置里的同步也没有效果。

**Comment by woolson** [comment]
@mzlogin 你能登录 🔗[网页端](https://todo.microsoft.com/)确认下数据是否已经同步到服务器了么？

**Comment by mzlogin** [comment]
嗯嗯  网页端是有数据的，Windows 客户端上也是可以看到的。

**Comment by woolson** [comment]
好的，谢谢
