### ISSUE TITLE
无法注销

### ISSUE THREAD

**Issue by mzlogin** [woolson/microsoft-todo-mac#13]
点击设置里的注销，会展示几秒登录界面，然后马上就会显示 loading，接着就要么一直 loading，要么自动回到主界面了。

**Comment by woolson** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/27878293/58782079-20d5ec00-8610-11e9-93ab-f691f5625f0d.png">

@mzlogin 可能在登录勾选了【使我保持登录状态】，影响了后面退出登录。
或许你可以先使用CMD+Q退出软件，然后重新打开后在注销。可以暂时使用这个方式退出，后面将会修复这个问题，谢谢反馈。

**Comment by yienzhu** [comment]
你好，同样问题CMD+Q退出后仍然无法注销。

**Comment by woolson** [comment]
@yienzhu 收到，近期版本更新后试试，谢谢反馈。

**Comment by yienzhu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，谢谢。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                yienzhu
                            
                    
                        
                            
                                    yienzhu@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年06月4日 13:38，Woolson · Lee<notifications@github.com> 写道： 


@yienzhu 收到，近期版本更新后试试，谢谢反馈。



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yienzhu** [comment]
谢谢，官方已经有mac版了，所以换了官方。

--
Yien

________________________________
发件人: Woolson ・ Lee <notifications@github.com>
发送时间: 星期六, 七月 27, 2019 9:12 下午
收件人: woolson/microsoft-todo-mac
抄送: yienzhu; Mention
主题: Re: [woolson/microsoft-todo-mac] 无法注销 (#13)


Closed #13<https://github.com/woolson/microsoft-todo-mac/issues/13>.

―
