### ISSUE TITLE
To Do Mac Login

### ISSUE THREAD

**Issue by APCronko** [woolson/microsoft-todo-mac#20]
Hello,

I input my email address and it tries to take me to the multiple account screen where I can select my Work Account but I am unable to do so because the blue circle goes round and round and never finishes loading the page.

![image](https://user-images.githubusercontent.com/51214757/58666346-b1eb5100-82f8-11e9-8f4d-1386fc7bf4d4.png)

**Comment by woolson** [comment]
@APCronko  Thank you for your report, maybe API does not support **work or school account**,  i'll check about that.(My english is bad, wish you know what i mean.)

**Comment by woolson** [comment]
@APCronko Hi, I have create a work account for validate this bug.
The account you used to login this app, it must can be used to login [outlook.com](https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=13&ct=1559544798&rver=7.0.6737.0&wp=MBI_SSL&wreply=https%3a%2f%2foutlook.live.com%2fowa%2f%3fRpsCsrfState%3d9164b2c6-0bee-a95a-c746-2e712ffba99f&id=292841&aadredir=1&CBCXT=out&lw=1&fl=dob%2cflname%2cwld&cobrandid=90015) successfully. Maybe you can use this app with a personal outlook email account. Thank you.
