### ISSUE TITLE
日历无法同步

### ISSUE THREAD

**Issue by unlockvvv** [woolson/microsoft-todo-mac#22]
share菜单里面貌似不可以直接从mac把一段文字share到to-do，日历好像也不能和outlook同步，是不是我设置方式有问题啊

**Comment by woolson** [comment]
你好，谢谢反馈。
1. share文字到todo：这个功能暂时没有（未来考虑加入）；
2. todo日历未和Outlook同步：目前todo内日历只显示设置了提醒时间的任务；

**Comment by woolson** [comment]
通过Mac分享到ToDo暂时无法实现，现在方式是：你复制一段文字，然后打开ToDo会有一个剪贴板浮窗可以创建任务了；
