### ISSUE TITLE
无法删除任务

### ISSUE THREAD

**Issue by wutea7** [woolson/microsoft-todo-mac#23]
首先表达一下感谢！因为我的是09年的MacBookPro，系统只能升级到10.11.6，官方应用不支持。所以非常非常感谢！！

登录、创建任务、设置提醒时间这些都没问题，但就是无法删除任务。

具体过程：点击右下角的垃圾桶按钮后，对话框提示是否确认删除，点击“是”后无任何反应，到网页版上检查任务仍在。

测试版本：2.2.4, 2.2.3

**Comment by woolson** [comment]
好的，我尽快修复这个问题。谢谢反馈。

**Comment by wutea7** [comment]
今天还发现了两个问题

1. 和上面的反馈一样，清单无法删除。

不同的是，删除任务的话，界面还是可以交互的；但是删除清单的话，整个界面都无法交互，没有停止响应，但要强制退出。

**Comment by woolson** [comment]
共享的看不到，微软那边接口获取不到共享清单数据。

**Comment by woolson** [comment]
新版`v2.2.5`已经处理好删除的BUG了，谢谢。
