### ISSUE TITLE
question: 看不到步骤的吗?

### ISSUE THREAD

**Issue by alex-czp** [woolson/microsoft-todo-mac#5]
如题, 点开任务看不到具体步骤

**Comment by woolson** [comment]
是的，微软的接口里面未提供步骤相关数据，后面如果接口更新我会更上去的😂

**Comment by alex-czp** [comment]
微软这接口开放这么多了, 怎么就没开放这一点点的接口呢……

**Comment by woolson** [comment]
我也很奇怪，但没找到，我给他们提issues了。

**Comment by woolson** [comment]
https://github.com/OfficeDev/outlook-dev-docs/issues/550

**Comment by woolson** [comment]
#https://github.com/OfficeDev/outlook-dev-docs/issues/550

**Comment by woolson** [comment]
#https://github.com/OfficeDev/outlook-dev-docs/issues/550

**Comment by Rainmna** [comment]
这个功能相当要命了，直接打6折。
没办法只能等了，已经去投过票了，大家都去投个票，也许有点用。

**Comment by woolson** [comment]
@Rainmna 是啊，还有我的一天也不错…真是醉了。

**Comment by woolson** [comment]
参见 #11
