### ISSUE TITLE
无法登录进去，几个小时了，重新退出登录也尝试了没用

### ISSUE THREAD

**Issue by gs666** [woolson/microsoft-todo-mac#7]
<img width="600" alt="WX20190404-175459@2x" src="https://user-images.githubusercontent.com/16437749/55546932-d238ce00-5702-11e9-9f5f-be9280a0c59a.png">

**Comment by woolson** [comment]
这个登录是微软那边的，你这边网络不稳定吗？

**Comment by gs666** [comment]
感谢回复，我关掉VPN后就顺利登录了，打扰了==

**Comment by woolson** [comment]
OK
